import articles from "@/content/articles.json";

export type Locale = "en" | "fa";
export type ArticleStatus = "draft" | "published";
export type Article = { id:string; translationGroup:string; locale:Locale; slug:string; title:string; deck:string; body:string; category:string; author:string; coverKey:string|null; coverTone:"sage"|"clay"|"night"; issue:string; status:ArticleStatus; publishedAt:string; createdAt:string; updatedAt:string };
export function localeFrom(value?: string | null): Locale { return value === "fa" ? "fa" : "en"; }

export const copy = {
  en: { journalEyebrow:"Independent · Bilingual · Reader-supported", heroTitle:"A quieter place for sharper ideas.", heroIntro:"Long-form arguments in English and Persian, built for readers who would rather understand a disagreement than perform one.", searchLabel:"Search articles", searchPlaceholder:"Search the journal", searchAction:"Search", searchResults:"Search results", clearSearch:"Clear search", featured:"Featured essay", latest:"Latest writing", readArticle:"Read essay", noResultsTitle:"Nothing matched that search.", noResultsBody:"Try a shorter phrase or return to the full journal.", openForum:"The open forum", principlesTitle:"Disagreement is welcome. Dehumanization is not.", principlesBody:"The comment room exists for challenge, correction and honest argument. Ideas receive no special protection; people retain their dignity.", principles:["Address the argument", "Bring evidence", "Protect private information"], mainNavigation:"Main navigation", articles:"Articles", about:"About", editor:"Editor", switchLanguage:"Read in Persian", footerLine:"Independent writing, without the noise.", communityRules:"Community rules" },
  fa: { journalEyebrow:"مستقل · دوزبانه · با پشتیبانی خوانندگان", heroTitle:"جایی آرام‌تر برای اندیشه‌های دقیق‌تر.", heroIntro:"مقاله‌های تحلیلی به فارسی و انگلیسی؛ برای خوانندگانی که ترجیح می‌دهند اختلاف را بفهمند، نه اینکه صرفاً آن را به نمایش بگذارند.", searchLabel:"جست‌وجوی مقاله‌ها", searchPlaceholder:"جست‌وجو در نشریه", searchAction:"جست‌وجو", searchResults:"نتایج جست‌وجو", clearSearch:"پاک‌کردن جست‌وجو", featured:"مقالهٔ برگزیده", latest:"تازه‌ترین نوشته‌ها", readArticle:"خواندن مقاله", noResultsTitle:"نتیجه‌ای پیدا نشد.", noResultsBody:"عبارت کوتاه‌تری را امتحان کنید یا به همهٔ مقاله‌ها برگردید.", openForum:"گفت‌وگوی آزاد", principlesTitle:"مخالفت آزاد است؛ تحقیر انسان‌ها نه.", principlesBody:"بخش دیدگاه‌ها برای نقد، اصلاح و گفت‌وگوی صادقانه ساخته شده است. هیچ ایده‌ای فراتر از نقد نیست؛ کرامت انسان‌ها اما باید حفظ شود.", principles:["به استدلال پاسخ دهید", "با سند سخن بگویید", "حریم خصوصی را حفظ کنید"], mainNavigation:"فهرست اصلی", articles:"مقاله‌ها", about:"درباره", editor:"سردبیر", switchLanguage:"مطالعه به انگلیسی", footerLine:"نوشتار مستقل، دور از هیاهو.", communityRules:"قواعد گفت‌وگو" },
} as const;
export function getCopy(locale: Locale) { return copy[locale]; }

export const sampleArticles = articles as Article[];
