/* eslint-disable @typescript-eslint/no-unused-expressions */
import http from "node:http";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { randomBytes, randomUUID } from "node:crypto";
import { extname, join, resolve, basename } from "node:path";
import { spawn } from "node:child_process";

const root = resolve(import.meta.dirname, "..");
const articlesPath = join(root, "content", "articles.json");
const coversPath = join(root, "public", "covers");
const token = randomBytes(24).toString("hex");
const port = 4179;

const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Azad Local Studio</title><style>
*{box-sizing:border-box}body{margin:0;background:#eeeae1;color:#1d2522;font:15px system-ui,sans-serif}.shell{display:grid;grid-template-columns:300px 1fr;min-height:100vh}aside{background:#17201d;color:#f5f0e7;padding:32px 22px}aside h1{font:700 28px Georgia;margin:0 0 6px}.sub{color:#aebbb5;margin:0 0 30px}.list{display:grid;gap:8px}.story{width:100%;text-align:left;padding:13px;border:1px solid #41504a;background:transparent;color:inherit;cursor:pointer}.story:hover,.story.active{background:#2d3b36}.story small{display:block;color:#aebbb5;margin-top:5px}.new{width:100%;padding:12px;margin-bottom:20px;background:#d7aa72;border:0;font-weight:700;cursor:pointer}main{padding:42px;max-width:1000px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.top h2{font:700 36px Georgia;margin:0}.notice{min-height:24px;color:#416956}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.full{grid-column:1/-1}label{display:grid;gap:7px;font-weight:650}input,select,textarea{width:100%;border:1px solid #b8b4aa;background:#faf8f2;padding:12px;font:inherit}textarea{resize:vertical}.body{min-height:360px;font-family:ui-monospace,monospace}.actions{display:flex;justify-content:flex-end;gap:12px;margin-top:22px}.save{background:#17201d;color:white;border:0;padding:13px 25px;font-weight:700;cursor:pointer}.cover{padding:18px;border:1px solid #b8b4aa}.cover img{width:180px;height:100px;object-fit:cover;display:block;margin-top:10px}@media(max-width:760px){.shell{display:block}aside{min-height:auto}.grid{grid-template-columns:1fr}.full{grid-column:auto}main{padding:24px}}
</style></head><body><div class="shell"><aside><h1>AZAD STUDIO</h1><p class="sub">Local editor · never published</p><button class="new" id="new">+ New article</button><div class="list" id="list"></div></aside><main><div class="top"><h2 id="heading">New article</h2><span id="notice" class="notice"></span></div><form id="form"><div class="grid"><label>Language<select name="locale"><option value="en">English</option><option value="fa">Persian</option></select></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Title<input name="title" maxlength="180" required></label><label>URL slug<input name="slug" maxlength="120" required></label><label>Category<input name="category" maxlength="60" value="Essay" required></label><label>Issue<input name="issue" maxlength="8" value="01" required></label><label class="full">Summary<textarea name="deck" rows="3" maxlength="420" required></textarea></label><label class="full">Article body (Markdown)<textarea class="body" name="body" maxlength="80000" required></textarea></label><div class="cover full"><label>Cover image (JPEG, PNG or WebP)<input id="cover" type="file" accept="image/jpeg,image/png,image/webp"></label><img id="preview" hidden alt="Cover preview"><input type="hidden" name="coverKey"><p>Images are re-encoded in your browser to remove camera/GPS metadata before saving.</p></div><label>Fallback color<select name="coverTone"><option value="sage">Sage</option><option value="clay">Clay</option><option value="night">Night</option></select></label><label>Translation group<input name="translationGroup" maxlength="80" placeholder="same value for EN and FA versions"></label></div><div class="actions"><button class="save" type="submit">Save locally</button></div></form></main></div><script>
const TOKEN=${JSON.stringify(token)};let articles=[],current=null;const form=document.querySelector('#form'),notice=document.querySelector('#notice'),list=document.querySelector('#list'),preview=document.querySelector('#preview');
const blank=()=>({id:null,translationGroup:'',locale:'en',slug:'',title:'',deck:'',body:'',category:'Essay',author:'Azad Journal',coverKey:null,coverTone:'sage',issue:'01',status:'draft',publishedAt:new Date().toISOString()});
function fill(a){current=a;document.querySelector('#heading').textContent=a.id?'Edit article':'New article';for(const [k,v] of Object.entries(a)){const el=form.elements.namedItem(k);if(el)el.value=v??''}preview.hidden=!a.coverKey;if(a.coverKey)preview.src='../covers/'+a.coverKey;render()}
function render(){list.innerHTML='';for(const a of articles){const b=document.createElement('button');b.className='story'+(current?.id===a.id?' active':'');b.innerHTML='<b></b><small></small>';b.querySelector('b').textContent=a.title||'Untitled';b.querySelector('small').textContent=a.locale.toUpperCase()+' · '+a.status;b.onclick=()=>fill({...a});list.appendChild(b)}}
async function load(){articles=await fetch('/api/articles').then(r=>r.json());fill(blank())}document.querySelector('#new').onclick=()=>fill(blank());
form.title.addEventListener('input',()=>{if(!current?.id)form.slug.value=form.title.value.normalize('NFKC').toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu,'-').replace(/^-+|-+$/g,'').slice(0,120)});
document.querySelector('#cover').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>8e6)return alert('Image is too large. Maximum 8 MB.');const img=new Image,imgUrl=URL.createObjectURL(file);await new Promise((ok,bad)=>{img.onload=ok;img.onerror=bad;img.src=imgUrl});const max=2400,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(imgUrl);const data=c.toDataURL('image/jpeg',.9);const name=(form.slug.value||'cover')+'.jpg';const result=await fetch('/api/cover',{method:'POST',headers:{'content-type':'application/json','x-studio-token':TOKEN},body:JSON.stringify({name,data})}).then(r=>r.json());if(result.error)return alert(result.error);form.coverKey.value=result.name;preview.src='../covers/'+result.name;preview.hidden=false};
form.onsubmit=async e=>{e.preventDefault();const a={...current,...Object.fromEntries(new FormData(form)),coverKey:form.coverKey.value||null,author:form.locale.value==='fa'?'نشریه آزاد':'Azad Journal'};const r=await fetch('/api/articles',{method:'POST',headers:{'content-type':'application/json','x-studio-token':TOKEN},body:JSON.stringify(a)}),result=await r.json();if(!r.ok){notice.textContent=result.error;return}articles=result.articles;notice.textContent='Saved. Commit and push when ready.';fill({...result.article});setTimeout(()=>notice.textContent='',4000)};load();
</script></body></html>`;

function send(res, status, data, type="application/json; charset=utf-8") { res.writeHead(status,{"content-type":type,"cache-control":"no-store","x-content-type-options":"nosniff"}); res.end(type.startsWith("application/json") ? JSON.stringify(data) : data); }
async function body(req, limit=2_000_000) { let size=0,chunks=[]; for await (const chunk of req) { size+=chunk.length;if(size>limit)throw new Error("Request is too large");chunks.push(chunk); } return JSON.parse(Buffer.concat(chunks).toString("utf8")); }
function validArticle(a) { if(!["en","fa"].includes(a.locale)||!["draft","published"].includes(a.status)||!a.title?.trim()||!a.slug?.trim()||!a.body?.trim()) throw new Error("Language, status, title, slug and body are required"); if(!/^[\p{L}\p{N}-]+$/u.test(a.slug)||a.slug.length>120) throw new Error("Slug may contain only letters, numbers and hyphens"); }

const server=http.createServer(async(req,res)=>{try{
  if(req.method==="GET"&&req.url==="/")return send(res,200,html,"text/html; charset=utf-8");
  if(req.method==="GET"&&req.url==="/api/articles")return send(res,200,JSON.parse(await readFile(articlesPath,"utf8")));
  if(req.method==="POST"&&req.headers["x-studio-token"]!==token)return send(res,403,{error:"Invalid local studio token"});
  if(req.method==="POST"&&req.url==="/api/articles"){const a=await body(req);validArticle(a);const all=JSON.parse(await readFile(articlesPath,"utf8"));if(all.some(x=>x.slug===a.slug&&x.id!==a.id))throw new Error("That URL slug is already in use");const now=new Date().toISOString();a.id=a.id||randomUUID();a.translationGroup=a.translationGroup||a.id;a.createdAt=a.createdAt||now;a.updatedAt=now;a.publishedAt=a.publishedAt||now;const i=all.findIndex(x=>x.id===a.id);i<0?all.push(a):all.splice(i,1,a);await writeFile(articlesPath,JSON.stringify(all,null,2)+"\n");return send(res,200,{article:a,articles:all});}
  if(req.method==="POST"&&req.url==="/api/cover"){const {name,data}=await body(req,12_000_000);if(!/^data:image\/jpeg;base64,/.test(data))throw new Error("Only sanitized JPEG data is accepted");const safe=basename(name).replace(/[^a-zA-Z0-9._-]/g,"-");if(extname(safe)!==".jpg")throw new Error("Invalid cover extension");const bytes=Buffer.from(data.split(",")[1],"base64");if(bytes.length>8_000_000)throw new Error("Image is too large");await mkdir(coversPath,{recursive:true});await writeFile(join(coversPath,safe),bytes,{flag:"wx"}).catch(async e=>{if(e.code!=="EEXIST")throw e;await writeFile(join(coversPath,safe),bytes)});return send(res,200,{name:safe});}
  send(res,404,{error:"Not found"});
}catch(error){send(res,400,{error:error instanceof Error?error.message:"Unable to save"})}});
server.listen(port,"127.0.0.1",()=>{const url=`http://127.0.0.1:${port}`;console.log(`Azad Local Studio: ${url}`);const [cmd,args]=process.platform==="win32"?["cmd",["/c","start","",url]]:process.platform==="darwin"?["open",[url]]:["xdg-open",[url]];spawn(cmd,args,{detached:true,stdio:"ignore"}).unref()});
